## what's new 

In [ ]:
# np.where

In [ ]:
# np.random.choice

In [129]:
# iterate over row and colums
x = np.arange(1, 10).reshape(3, 3)

In [130]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
for row in x:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [132]:
for row in x.T:
    print(row)

[1 4 7]
[2 5 8]
[3 6 9]


In [106]:
# numpy.diagonal
x = np.arange(1, 10).reshape(3, 3)

In [107]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
x.diagonal()

array([1, 5, 9])

In [127]:
np.diagonal(x)

array([1, 5, 9])

In [126]:
np.flipud(x).diagonal()[::-1]

array([3, 5, 7])

In [ ]:
# -----------------------------------

In [1]:
import numpy as np

In [2]:
def create_board():
    return np.zeros((3, 3))

board = create_board()

In [3]:
board

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
def place(board, player, position):
    if board[position] == 0:
        board[position] = player

In [6]:
board[1, 1] = 1

In [7]:
board

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
ind = np.where(board == 0)

In [21]:
list(zip(list(ind[0]), list(ind[1])))

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]

In [24]:
list(zip(ind[0], ind[1]))

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]

In [25]:
def possibilities(board):
    not_occupied = np.where(board == 0)
    return list(zip(not_occupied[0], not_occupied[1]))

In [26]:
possibilities(board)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]

In [78]:
# -------------------------------

In [86]:
board = create_board()

In [87]:
board

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [168]:
np.random.seed()

In [89]:
def random_place(board, player):
    positions = possibilities(board)
    if (len(positions) > 0):
        index = np.random.randint(0, len(positions))
        position = positions[index]
        place(board, player, position)

In [90]:
random_place(board, 2)

In [91]:
board

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  2.],
       [ 0.,  0.,  0.]])

In [92]:
# -------------------

In [93]:
board = create_board()
for i in range(3):
    for player in [1, 2]:
        random_place(board, player)

print(board)

[[ 1.  0.  1.]
 [ 0.  2.  1.]
 [ 2.  0.  2.]]


In [ ]:
# -----------------------

In [94]:
def check_row(row, player):
    for marker in row:
        if marker != player:
            return False
    return True        


def row_win(board, player):
    for i in range(board.shape[0]):
        if not check_row(board[i], player):
            return False
    return True

In [95]:
row_win(board, 1)

False

In [180]:
def row_win(board, player):
    for row in board:
        if check_row(row, player):
            return True
    return False

In [181]:
x = np.arange(1, 10).reshape(3,3)

In [182]:
x[0, 1] = 1
x[0, 2] = 1

In [183]:
x

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
row_win(x, 1)

True

In [96]:
# -------------------------

In [190]:
def col_win(board, player):
    for row in board.T:
        if check_row(row, player):
            return True
    return False

In [100]:
col_win(board, 1)

False

In [135]:
# --------------------------

In [186]:
def diag_win(board, player):
    main_diag = board.diagonal()
    anti_diag = np.flipud(board).diagonal()[::-1]
    return check_row(main_diag, player) or check_row(anti_diag, player)

In [133]:
# --------------------------

In [134]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        # Check if `row_win`, `col_win`, or `diag_win` apply.  if so, store `player` as `winner`.
        if row_win(board, player) or diag_win(board, player) or col_win(board, player):
            return player
    if np.all(board != 0):
        winner = -1
    return winner

In [136]:
# --------------------------

In [137]:
def play_game():
    board = create_board()
    while True:
        for player in [1, 2]:
            random_place(board, player)
            print(board)
            result = evaluate(board)
            if result != 0:
                return result

In [166]:

play_game()

-1

In [ ]:
# -------------------

In [191]:
ITERATIONS = 100
result = []
for i in range(ITERATIONS):
    result.append(play_game())

print(result[:100])

[1, 1, 1, 2, 1, 2, -1, 1, 2, 1, -1, -1, -1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, -1, 1, 1, -1, 1, 1, -1, 2, 2, 2, 2, 2, -1, -1, 2, -1, 1, 1, 2, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2]


In [171]:
! git add .; git ci -m "done hw2"; git push

[master 24df9ee] done hw2
 1 file changed, 981 insertions(+)
 create mode 100644 homework/hw2/hw2.ipynb
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 2.15 KiB | 0 bytes/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To github.com:ilyarudyak/PH526x_python_research.git
   aaa3a18..24df9ee  master -> master


In [192]:
! git add .; git ci -m "fix some bugs"; git push

[master 6992d2d] fix some bugs
 2 files changed, 193 insertions(+), 22 deletions(-)
 create mode 100644 homework/hw2/tic_tac_toe.py
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.72 KiB | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:ilyarudyak/PH526x_python_research.git
   24df9ee..6992d2d  master -> master
