##  Part 1: Scope Rules and Classes

In [12]:
def update(n, x):
    n = 2 # n is local variable so n from main is NOT changed
    x.append(4) # mutate x here 
    print('update: n={} x={}'.format(n, x))

In [13]:
def main():
    n = 1
    x = [0, 1, 2, 3]
    print('  main: n={} x={}'.format(n, x))
    update(n, x)
    print('  main: n={} x={}'.format(n, x))

In [14]:
main()

  main: n=1 x=[0, 1, 2, 3]
update: n=2 x=[0, 1, 2, 3, 4]
  main: n=1 x=[0, 1, 2, 3, 4]


In [15]:
def increment(n): 
   n += 1 
   print(n) 

n = 1 
increment(n) 
print(n)

2
1


In [16]:
def increment(n):
   n += 1
   return n

n = 1
while n < 10:
   n = increment(n)
print(n)

10


In [17]:
! git add .; git ci -m "done part 1"; git push

[master cd749b9] done part 1
 3 files changed, 891 insertions(+), 14 deletions(-)
 create mode 100644 input.txt
 create mode 100644 week2.ipynb
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 3.03 KiB | 0 bytes/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To github.com:ilyarudyak/PH526x_python_research.git
   b4f70f9..cd749b9  master -> master


## Part 2: NumPy

In [18]:
import numpy as np

In [19]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros(5, 0.)

TypeError: data type not understood

In [22]:
np.zeros(0,0,0,0,0)

TypeError: function takes at most 3 arguments (5 given)

In [23]:
np.array(0,0,0,0,0)

ValueError: only 2 non-keyword arguments accepted

In [26]:
x = np.array([[3,6],[5,7]])
print(x)
y = x.transpose() 
print(y) 

[[3 6]
 [5 7]]
[[3 5]
 [6 7]]


In [27]:
x = np.array([1,2,5]) 
x[1:2]

array([2])

In [28]:
a = np.array([1,2]) 
b = np.array([3,4,5]) 
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

### Indexing NumPy Arrays

In [29]:
z1 = np.array([1, 3, 5, 7, 9])

In [30]:
z2 = z1 + 1

#### index numpy array with list or other array

In [31]:
ind = [0, 2, 3]

In [32]:
z1[ind]

array([1, 5, 7])

In [33]:
ind = np.array(ind)

In [34]:
z1[ind]

array([1, 5, 7])

#### logical indexing

In [35]:
z1

array([1, 3, 5, 7, 9])

In [36]:
z1 > 6

array([False, False, False,  True,  True], dtype=bool)

In [37]:
z1[z1 > 6]

array([7, 9])

In [38]:
z2

array([ 2,  4,  6,  8, 10])

In [39]:
z2[z1 > 6]

array([ 8, 10])

In [40]:
ind = z1 > 6

In [41]:
ind

array([False, False, False,  True,  True], dtype=bool)

In [42]:
z1[ind]

array([7, 9])

In [43]:
z2[ind]

array([ 8, 10])

#### slicing returns view, not copy; but indexing return copy

In [44]:
z1 = np.array([1, 3, 5, 7, 9])

In [51]:
# first lets look at slicing
w = z1[0:3]

In [46]:
w

array([1, 3, 5])

In [48]:
w[0] = 100

In [50]:
# content of z1 was modified
z1

array([100,   3,   5,   7,   9])

In [52]:
# now lets look at indexing
z1 = np.array([1, 3, 5, 7, 9])
ind = [0, 1, 2]
w = z1[ind]

In [53]:
w

array([1, 3, 5])

In [54]:
w[0] = 100

In [55]:
w

array([100,   3,   5])

In [58]:
# content of z1 is NOT modified
z1

array([1, 3, 5, 7, 9])

In [59]:
# ---------------------------

In [60]:
a = np.array([1,2]) 
b = np.array([3,4,5]) 
b[a]

array([4, 5])

In [62]:
a = np.array([1,2]) 
b = np.array([3,4,5]) 
c = b[1:] 
print("b[a]={} c={}".format(b[a], c))
b[a] is c 

b[a]=[4 5] c=[4 5]


False

### Building and Examining NumPy Arrays

#### linspace( )

In [64]:
np.linspace(10, 100, 10)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,  100.])

In [66]:
# log(10) = 1, log(100) = 2
np.logspace(1, 2, 10)

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

In [67]:
np.logspace(np.log10(10), np.log10(100), 10)

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

#### shape, size

In [68]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [69]:
X.shape

(2, 3)

In [70]:
X.size

6

#### any( ), all( )

In [76]:
x = np.random.random(10)

In [77]:
x

array([ 0.0065733 ,  0.78814923,  0.30292532,  0.01148002,  0.67662474,
        0.9686008 ,  0.89514686,  0.99759949,  0.97631278,  0.13017601])

In [80]:
np.any(x > 0.9)

True

In [79]:
np.all(x > 0.1)

False

In [81]:
np.all(x > 0.01)

False

In [82]:
np.all(x > 0.001)

True

In [83]:
# -------------------------------

In [84]:
x = 20

In [85]:
[x%i == 0 for i in range(2, x)]

[True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [86]:
np.any([x%i == 0 for i in range(2, x)])

True

In [87]:
not np.any([x%i == 0 for i in range(2, x)])

False